--RECEPCION DE PLANTA
select * from ingresosalidaalm where idmotivo = 'IAC'
SELECT * FROM DINGRESOSALIDAALM 
--ALMACEN DE MATERIA PRIMA
select * from ingresosalidaalm where idmotivo = 'STP'
SELECT * FROM DINGRESOSALIDAALM 
--VOLCADO DE MATERIA PRIMA A LINEAS
SELECT * FROM DORDENVOLCADO_LINEA
SELECT * FROM ORDENVOLCADO
SELECT * FROM DORDENVOLCADO_CONSUMIDOR
--REGISTRO DE PALETAS
SELECT * FROM REGISTROPALETA
SELECT * FROM DREGISTROPALETA
--INGRESOS A TUNEL DE FRIO
SELECT * FROM INGRESOSALIDATUNEL
SELECT * FROM DINGRESOSALIDATUNEL
--PARTES DE TRANSFORMACION
SELECT * FROM INGRESOSALIDAPROCESO
SELECT * FROM DINGRESOSALIDAPROCESO WHERE IDINGRESOSALIDAPROCESO = '_5VW0N021944473'
SELECT * FROM DDINGRESOSALIDAPROCESO WHERE IDINGRESOSALIDAPROCESO = '_5VW0N021944473'
SELECT * FROM DDDINGRESOSALIDAPROCESO WHERE IDINGRESOSALIDAPROCESO = '_5VW0N021944473'
SELECT * FROM DINGRESOSALIDAPROCESO_COSTOS WHERE IDINGRESOSALIDAPROCESO = '_5VW0N021944473'
SELECT * FROM DINGRESOSALIDAPROCESO_DISTRIBUIDO WHERE IDINGRESOSALIDAPROCESO = '_5VW0N021944473'
SELECT * FROM DDINGRESOSALIDAPROCESO_REFERENCIAS WHERE IDINGRESOSALIDAPROCESO = '_5VW0N021944473'
--PREPACKINGLIST
SELECT * FROM PREPACKINGLIST
SELECT * FROM DPREPACKINGLIST
SELECT * FROM DDPREPACKINGLIST
--PACKINGLIST
SELECT * FROM PACKINGLIST
SELECT * FROM DPACKINGLIST
SELECT * FROM DDPACKINGLIST
SELECT * FROM DDISTRIBUCIONPALETAS_CONTENEDOR

